spring:
  application:
    name: spring-swagger

#swagger:
#  butler:
#    resources[0]:
#      name: service-a
#      url: /service-a/v2/api-docs
#      swagger-version: 2.0
#    resources[1]:
#      name: service-b
#      url: /service-b/v2/api-docs
#      swagger-version: 2.0
#  show: true

swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}
