spring:
  application:
    name: spring-redis
  redis:
    database: 1
    timeout: 10000ms
    host: 127.0.0.1
    port: 6379
    password: null

redisson:
  codec: org.redisson.codec.JsonJacksonCodec
  threads: 4
  netty:
    threads: 4
  single-server-config:
    address: "redis://localhost:6379"
    password: null
    database: 0
  # 自定义配置
  lock:
    key:

management:
  endpoints:
    web:
      exposure:
#        include: info, health, beans, env, metrics
        include: '*'