server:
  port: 8001
dubbo:
  application:
    name: provider
    qos-enable: false
    qos-accept-foreign-ip: false
  protocol:
    name: dubbo
    port: -1
  registry:
    #address: nacos://cloud.rm:8828
    address: nacos://192.168.1.8:8848
    username: nacos
    password: nacos
    parameters:
      namespace: 9213ea6c-a259-4251-9767-b12d1e8fe1a3
      group: spring-boot

#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: http://localhost:8848
#        username: nacos
#        password: nacos
#      config:
#        server-addr: http://localhost:8848
#        file-extension: properties
#        username: nacos
#        password: nacos