spring:
  datasource:
    url: jdbc:mysql://${mysql_host}/boot?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${mysql_username}
    password: ${mysql_password}
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    check-template-location: false
  redis:
    database: 0
    host: ${redis_host}
    port: ${redis_port}
    password: ${redis_password}


# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:mybatis/mappers/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.leone.boot.shiro.entity
  global-config:
    banner: false
    db-config:
      # 主键类型
      id-type: auto
      # 字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      # 逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 是否开启大写命名，默认不开启
      capital-mode: false
      # 表名、是否使用下划线命名，默认数据库表使用下划线命名
      table-underline: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

app:
  shiro:
    secret: NDg2OTQ=
    multiLogin: true
    loginUrl: /shiro/login
    logoutUrl: /shiro/logout
    anonUrls:
      - /shiro/upload
      - /shiro/test
      - /shiro/image
      - /shiro/login
    authUrls: /**

  token:
    headerName: token
    duration: 720
    redisPrefix: token
    tokenPrefix: token_cache
    secret: u81kl*&
