spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql_host}/boot?useSSL=false&characterEncoding=utf8&allowMultiQueries=true
    username: ${mysql_username}
    password: ${mysql_password}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    show-sql: true
    open-in-view: false

