server:
  port: 8085

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    open-in-view: false
  datasource:
    url: jdbc:mysql://ip:port/db?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: xxx
    password: xxx
  quartz:
    jdbc:
      initialize-schema: never
      schema: classpath:quartz_schema.sql
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            useProperties: false
            dataSource: myDs
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
          dataSource:
            myDs:
              driver: com.mysql.jdbc.Driver
              URL: jdbc:mysql://ip:port/db?useSSL=false
              user: xxx
              password: xxx
