spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot?useSSL=false
    username: xxxx
    password: xxxx
  batch:
    job:
      enabled: true
    initialize-schema: always
