spring:
  application:
    name: spring-redis
  profiles:
    active: redis

management:
  endpoints:
    web:
      exposure:
        # include: info, health, beans, env, metrics
        include: '*'