spring:
  data:
    redis:
      database: 0
      host: ${redis_host}
      port: ${redis_port}
      username: default
      password: ${redis_password}
      ssl:
        enabled: true
  redis:
    redisson:
      file: classpath:redisson.yml

redisson:
  # 自定义配置
  lock:
    key: lock

redis:
  prefix: app