spring:
  application:
    name: websocket
server:
  servlet:
    context-path: /ws
#  ssl:
#    key-store: tomcat.keystore
#    key-password: 123456
#    key-store-type: PKCS12
#    key-alias: tomcat
custom:
  id: 12
  name: kobe

  logging:
    level: DEBUG