spring:
  data:
    redis:
      host: ${redis_host}
      port: ${redis_port}
      password: ${redis_password}
      ssl:
        enabled: true
  redis:
    redisson:
      file: classpath:redisson.yml

jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson2
  remote:
    default:
      type: redisson
      keyConvertor: fastjson2
      broadcastChannel: ${spring.application.name}
      keyPrefix: ${spring.application.name}
      valueEncoder: java
      valueDecoder: java
      defaultExpireInMillis: 5000