spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      ssl:
        enabled: true
  redis:
    redisson:
      file: classpath:redisson.yml

jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson2
  remote:
    default:
      type: redisson
      keyConvertor: fastjson2
      broadcastChannel: ${spring.application.name}
      keyPrefix: ${spring.application.name}
      valueEncoder: java
      valueDecoder: java
      defaultExpireInMillis: 5000